name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yy)$(DayOfYear).$(BuildCounter)

parameters:
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    displayName: "Continue even if resources are getting destroyed"
    type: boolean
    default: false

trigger:
  - main
  - release/*
  - develop

schedules:
- cron: "0 4 * * 1"
  displayName: "Weekly NVD Check Build"
  branches:
    include:
    - main
  always: true

pool: 
    name: NautilusBuild
    demands: vs_16 -equals 1 #exclude agents 13 and 14 as code coverage report fails

variables:
  - name: BuildConfiguration
    value: "release"
  - name: BuildPlatform
    value: "any cpu"
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: UKHOAssemblyCompany
    value: "UK Hydrographic Office"
  - name: UKHOAssemblyVersionPrefix
    value: "1.0."
  - name: UKHOAssemblyProduct
    value: "External Notification Service"
  - name: UKHOAssemblyCopyright
    value: "Copyright © UK Hydrographic Office"
  - name: Container
    value: "ukhydrographicoffice/terraform-azure-powershell-unzip:1.9.6"
  - name: DeploymentPool
    value: "Mare Nectaris"
  - name: WindowPool
    value: "NautilusBuild"

stages:
  - stage: BuildTestPublish
    displayName: "Build, test and publish"
    dependsOn: []
    jobs:
    - template: Deployment/templates/build-test-publish.yml  
      parameters:
        DotNetVersion: '8.0.x'


  - stage: IATDeploy
    dependsOn:
    - BuildTestPublish
    displayName: "IATDeploy (inc terraform, webapp deploy)"
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    jobs:
    - template: Deployment/templates/app-deploy.yml
      parameters:
        ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
        AzureEnvironment: "Ens-IAT"
        ShortName: "IAT"
        ApimShortName: "NonLive"
        AzureSubscriptionVersion: "IAT - A.011.08"
        RunFunctionalTests: true
        Container: ${{variables.Container}}


  - stage: PreProdDeploy
    dependsOn:
    - BuildTestPublish
    displayName: "PreProdDeploy (inc terraform, webapp deploy)"
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    jobs:
    - template: Deployment/templates/app-deploy.yml
      parameters:
        ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
        AzureEnvironment: "Ens-Pre"
        ShortName: "Pre"
        ApimShortName: "NonLive"
        AzureSubscriptionVersion: "PRE- A.011.08"
        RunFunctionalTests: true
        Container: ${{variables.Container}}      
  
