name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yy)$(DayOfYear).$(BuildCounter)

parameters:
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    displayName: "Continue even if resources are getting destroyed"
    type: boolean
    default: true

trigger:
  - main
  - release/*
  - develop

pool: 
    name: NautilusBuild
    demands: vs_16 -equals 1 #exclude agents 13 and 14 as code coverage report fails

variables:
  - name: BuildConfiguration
    value: "release"
  - name: BuildPlatform
    value: "any cpu"
  - name: BuildCounter
    value: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  - name: UKHOAssemblyCompany
    value: "UK Hydrographic Office"
  - name: UKHOAssemblyVersionPrefix
    value: "1.0."
  - name: UKHOAssemblyProduct
    value: "External Notification Service"
  - name: UKHOAssemblyCopyright
    value: "Copyright © UK Hydrographic Office"
  - name: Container
    value: "ukhydrographicoffice/terraform-azure-powershell-unzip:1.7.2"
  - name: DeploymentPool
    value: "UKHO Ubuntu 1804"
  - name: WindowPool
    value: "NautilusBuild"

stages:
  - stage: PERFORM_DEPENDENCYCHECK_DOTNETBUILD_DOTNETTEST_AND_PUBLISH
    displayName: "Build (inc DependencyChecker, Dotnet Build , dotnet test and publish artifact )"
    dependsOn: []
    jobs:
      - job: PublishFunctionalTestsAndTerraform
        workspace:
          clean: all
        displayName: "Publish Functional Tests And Terraform"
        steps:
          - task: PublishBuildArtifacts@1
            displayName: "Publish terraform Artifacts"
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)\Deployment'
              ArtifactName: terraformartifact

  - stage: Devdeploy
    displayName: "Devdeploy (inc terraform, webapp deploy)"
    jobs:
      - deployment: DevDeployApp
        displayName: "Dev - deploy terraform and dotnet App"
        environment: "Ens-Dev"
        pool: $(DeploymentPool)
        container: ${{variables.Container}}
        workspace:
          clean: all
        variables:
          - group: "ENS-Dev-TF-Variables"
          - group: "ENS-Dev-Variables" 
          - name: "D365AuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-TENANT-ID)
          - name: "D365AuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-CLIENT-ID)
          - name: "D365AuthConfiguration.ClientSecret"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-SECRET-VALUE)
          - name: "EnsAuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-CLIENT-ID)
          - name: "EnsAuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-TENANT-ID)
          - name: "ElasticAPM.ApiKey"
            value: $(elasticAPM-ApiKey)
          - name: "ElasticAPM.Environment"
            value: $(elasticAPM-Environment)
          - name: "ElasticAPM.ServerURL"
            value: $(elasticAPM-ServerURL)
          - name: "ElasticAPM.ServiceName"
            value: $(elasticAPM-ServiceName)
          - name: "ElasticAPM.WebJobServiceName"
            value: $(elasticAPM-WebJobServiceName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Deployment/templates/continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: "External Notification Service Dev - A.008.02"
                    NewId1: "/subscriptions/db328b32-0563-44a5-8f51-689c5cae8a7e/resourceGroups/ens-dev-rg/providers/Microsoft.Web/sites/ens-dev-webapp"
                    NewId2: "/subscriptions/db328b32-0563-44a5-8f51-689c5cae8a7e/resourceGroups/ens-dev-rg/providers/Microsoft.Web/sites/ens-dev-webapp/slots/staging"
                    NewId3: "/subscriptions/db328b32-0563-44a5-8f51-689c5cae8a7e/resourceGroups/ens-dev-rg/providers/Microsoft.Web/sites/ens-dev-webapp-stub"

  - stage: IATvNextDeploy
    dependsOn:
      - DevDeploy
    displayName: "IATvNextDeploy (inc terraform, webapp deploy)"
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'),startsWith(variables['Build.SourceBranch'], 'refs/heads/dev/')))
    jobs:
      - deployment: IATvNextDeployApp
        displayName: IATvNext - deploy terraform and dotnet App
        environment: "Ens-IATvNext"
        pool: $(DeploymentPool)
        container: ${{variables.Container}}
        workspace:
          clean: all
        variables:
          - group: "ENS-IAT-VNext-TF-Variables"
          - group: "ENS-IAT-VNext-Variables"
          - name: "D365AuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-TENANT-ID)
          - name: "D365AuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-CLIENT-ID)
          - name: "D365AuthConfiguration.ClientSecret"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-SECRET-VALUE)
          - name: "EnsAuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-CLIENT-ID)
          - name: "EnsAuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-TENANT-ID)
          - name: "ElasticAPM.ApiKey"
            value: $(elasticAPM-ApiKey)
          - name: "ElasticAPM.Environment"
            value: $(elasticAPM-Environment)
          - name: "ElasticAPM.ServerURL"
            value: $(elasticAPM-ServerURL)
          - name: "ElasticAPM.ServiceName"
            value: $(elasticAPM-ServiceName)
          - name: "ElasticAPM.WebJobServiceName"
            value: $(elasticAPM-WebJobServiceName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Deployment/templates/continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: "External Notification Service vNext IAT - A.011.08"
                    NewId1: ""
                    NewId2: ""
                    NewId3: ""
                  parameters:
                    TestTitle: "IAT-AutomationTests"
  
  - stage: E2EvNextDeploy
    dependsOn:
      - IATvNextDeploy
    displayName: E2EvNextDeploy (inc terraform, webapp deploy)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - deployment: E2EvNextDeployApp
        displayName: E2EvNext - deploy terraform and dotnet App
        environment: "Ens-E2EvNext"
        pool: $(DeploymentPool)
        container: ${{variables.Container}}
        workspace:
          clean: all
        variables:
          - group: "ENS-E2E-VNext-TF-Variables"
          - group: "ENS-E2E-VNext-Variables"
          - name: "D365AuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-TENANT-ID)
          - name: "D365AuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-CLIENT-ID)
          - name: "D365AuthConfiguration.ClientSecret"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-SECRET-VALUE)
          - name: "EnsAuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-CLIENT-ID)
          - name: "EnsAuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-TENANT-ID)
          - name: "ElasticAPM.ApiKey"
            value: $(elasticAPM-ApiKey)
          - name: "ElasticAPM.Environment"
            value: $(elasticAPM-Environment)
          - name: "ElasticAPM.ServerURL"
            value: $(elasticAPM-ServerURL)
          - name: "ElasticAPM.ServiceName"
            value: $(elasticAPM-ServiceName)
          - name: "ElasticAPM.WebJobServiceName"
            value: $(elasticAPM-WebJobServiceName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Deployment/templates/continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: "External Notification Service vNext E2E - A.011.08"
                    NewId1: ""
                    NewId2: ""
                

  - stage: QAdeploy
    dependsOn:
      - DevDeploy
    displayName: QAdeploy (inc terraform, webapp deploy)
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    jobs:
      - deployment: QADeployApp
        displayName: QA - deploy terraform and dotnet App
        environment: "Ens-Qa"
        pool: $(DeploymentPool)
        container: ${{variables.Container}}
        workspace:
          clean: all
        variables:
          - group: "ENS-QA-TF-Variables"
          - group: "ENS-QA-Variables"
          - name: "D365AuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-TENANT-ID)
          - name: "D365AuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-CLIENT-ID)
          - name: "D365AuthConfiguration.ClientSecret"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-SECRET-VALUE)
          - name: "EnsAuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-CLIENT-ID)
          - name: "EnsAuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-TENANT-ID)
          - name: "ElasticAPM.ApiKey"
            value: $(elasticAPM-ApiKey)
          - name: "ElasticAPM.Environment"
            value: $(elasticAPM-Environment)
          - name: "ElasticAPM.ServerURL"
            value: $(elasticAPM-ServerURL)
          - name: "ElasticAPM.ServiceName"
            value: $(elasticAPM-ServiceName)
          - name: "ElasticAPM.WebJobServiceName"
            value: $(elasticAPM-WebJobServiceName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Deployment/templates/continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: "External Notification Service QA - A.008.02"
                    NewId1: ""
                    NewId2: ""
                    NewId3: ""

  - stage: Livedeploy
    dependsOn:
      - QADeploy
    displayName: Livedeploy (inc terraform, webapp deploy)
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'),startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
    jobs:
      - deployment: LiveDeployApp
        displayName: Live - deploy terraform and dotnet App
        environment: "Ens-Live"
        pool: $(DeploymentPool)
        container: ${{variables.Container}}
        workspace:
          clean: all
        variables:
          - group: "ENS-Live-TF-Variables"
          - group: "ENS-Live-Variables"
          - name: "D365AuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-TENANT-ID)
          - name: "D365AuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-CLIENT-ID)
          - name: "D365AuthConfiguration.ClientSecret"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-SECRET-VALUE)
          - name: "EnsAuthConfiguration.ClientId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-CLIENT-ID)
          - name: "EnsAuthConfiguration.TenantId"
            value: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-TENANT-ID)
          - name: "ElasticAPM.ApiKey"
            value: $(elasticAPM-ApiKey)
          - name: "ElasticAPM.Environment"
            value: $(elasticAPM-Environment)
          - name: "ElasticAPM.ServerURL"
            value: $(elasticAPM-ServerURL)
          - name: "ElasticAPM.ServiceName"
            value: $(elasticAPM-ServiceName)
          - name: "ElasticAPM.WebJobServiceName"
            value: $(elasticAPM-WebJobServiceName)
        strategy:
          runOnce:
            deploy:
              steps:
                - template: Deployment/templates/continuous-deployment.yml
                  parameters:
                    ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                    AzureSubscription: "External Notification Service Live - A.008.02"
                    NewId1: ""
                    NewId2: ""
                    NewId3: ""
