openapi: '3.0.1'
info:
  title: UKHO External Notification Service Monitor APIs
  description: "This is a light weight open api spec for UKHO External Notification Service Monitor and it should not be used as formal API documentation. One of its main purpose is to allow importing ENS Monitor APIs in APIM."
  version: '0.0.1'
  contact:
    email: AbzuDeliveryTeam@ukho.gov.uk
    name: Abzu Team
paths:
  /health:
    get:
      summary: "Health Check."
      operationId: "healthCheck"
      description: "Returns the health status of the application"
      responses:
        200:
          description: "Healthy"
        503:
          description: "Unhealthy"
