parameters:
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    type: boolean
    default: false
  - name: AzureSubscription
    type: string
  - name: TerraformKeyVault
    type: string
  - name: APIMResourceGroup
    type: string
  - name: APIMServiceInstance
    type: string
  - name: tfstateStorageAccountName
    type: string

steps:
  - task: AzureKeyVault@2
    displayName: 'Read APIM terraform Variables'
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      KeyVaultName: "${{ parameters.TerraformKeyVault }}"
      SecretsFilter: '*'
      RunAsPreJob: false

  - task: PowerShell@2
    name: APIMDeployment
    displayName: "terraform APIM deployment"
    inputs:
      targetType: filePath
      filePath: '$(Pipeline.Workspace)/terraformartifact/terraform_conditional_run_apim.ps1'
      arguments: '-deploymentResourceGroupName ${{ parameters.APIMResourceGroup }} -deploymentStorageAccountName ${{ parameters.tfstateStorageAccountName }} -workSpace $(Environment) -continueEvenIfResourcesAreGettingDestroyed $${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}'
    env:
      ARM_CLIENT_ID: $(TERRAFORM-CLIENT-ID)
      ARM_CLIENT_SECRET: $(TERRAFORM-CLIENT-SECRET)
      ARM_TENANT_ID: $(TERRAFORM-TENANT-ID)
      ARM_SUBSCRIPTION_ID: $(TERRAFORM-SUBSCRIPTION-ID)
      TF_VAR_resource_group_name: ${{ parameters.APIMResourceGroup }}
      TF_VAR_apim_service_name: ${{ parameters.APIMServiceInstance }}
      TF_VAR_apim_api_service_url: $(SERVICE_DNS_URL)
      TF_VAR_ad_tenant_id: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-TENANT-ID)
      TF_VAR_client_credentials_client_id: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-CLIENT-ID)
      TF_VAR_client_credentials_secret: $(EXTERNAL-NOTIFICATION-SERVICE-APIM-CLIENT-SECRET-VALUE)
      TF_VAR_client_credentials_scope: "$(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-CLIENT-ID)/.default"
      TF_VAR_ens_app_client_id: $(EXTERNAL-NOTIFICATION-SERVICE-APP-REGISTRATION-CLIENT-ID)
      TF_VAR_d365_product_daily_quota_limit: $(d365productquotalimit)
      TF_VAR_d365_product_call_limit: $(d365productcalllimit)
      TF_VAR_d365_product_call_renewal_period: $(d365productrenewalperiod)
      TF_VAR_ees_product_call_limit: $(eesproductcalllimit)
