parameters:
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    type: boolean
    default: false
  - name: AzureSubscription
    type: string
  - name: NewId1
    type: string
  - name: NewId2
    type: string
  - name: NewId3
    type: string

steps:
  # - task: FileTransform@2
  #   displayName: "File Transform: Ens Config" #Replace ens instance value from pipeline 
  #   inputs:
  #     folderPath: '$(Pipeline.Workspace)/terraformartifact/src'
  #     xmlTransformationRules:
  #     jsonTargetFiles: 'appsettings.json'

  - task: PowerShell@2
    displayName: "terraform $(Environment)update"
    name: TfUpdate
    inputs:
      targetType: filePath
      filePath: '$(Pipeline.Workspace)/terraformartifact/terraform_remove.ps1'
      arguments: '-deploymentResourceGroupName $(DeploymentResourceGroupName) -deploymentStorageAccountName $(DeploymentStorageAccountName) -workSpace $(Environment) -elasticApmServerUrl $(ElasticAPM.ServerURL) -elasticApmApiKey $(ElasticAPM.ApiKey) -newId1 "$${{ parameters.NewId1 }}" -newId2 "$${{ parameters.NewId2 }}" -newId3 "$${{ parameters.NewId3 }}"'
    env:
      ARM_CLIENT_ID: $(TERRAFORM-CLIENT-ID)
      ARM_CLIENT_SECRET: $(TERRAFORM-CLIENT-SECRET)
      ARM_TENANT_ID: $(TERRAFORM-TENANT-ID)
      ARM_SUBSCRIPTION_ID: $(TERRAFORM-SUBSCRIPTION-ID)
      TF_VAR_allowed_ips: $(whiteListedIps)
      TF_VAR_spoke_rg: $(spokeRG)
      TF_VAR_spoke_vnet_name: $(spokeVnetName)
      TF_VAR_spoke_subnet_name: $(spokeSubnetName)
      TF_VAR_agent_rg: $(agentRG)
      TF_VAR_agent_vnet_name: $(agentVnetName)
      TF_VAR_agent_subnet_name: $(agentSubnetName)
      TF_VAR_agent_subscription_id: $(agentSubscriptionId)
      TF_VAR_private_endpoint_subnet_name: $(privateEndpointSubnet)
      TF_VAR_core_services_subscription_id: $(coreServicesSubscriptionId)
      TF_VAR_core_services_rg: $(coreServicesRG)

  # - task: PowerShell@2
  #   displayName: "terraform $(Environment)deploy"
  #   name: TfCreate
  #   inputs:
  #     targetType: filePath
  #     filePath: '$(Pipeline.Workspace)/terraformartifact/terraform_conditional_run.ps1'
  #     arguments: '-deploymentResourceGroupName $(DeploymentResourceGroupName) -deploymentStorageAccountName $(DeploymentStorageAccountName) -workSpace $(Environment) -continueEvenIfResourcesAreGettingDestroyed $${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }} -terraformJsonOutputFile $(Pipeline.Workspace)/terraformartifact/terraform_output.json -elasticApmServerUrl $(ElasticAPM.ServerURL) -elasticApmApiKey $(ElasticAPM.ApiKey) -elasticApmEnvironment "$(ElasticAPM.Environment)" -elasticApmWebJobServiceName "$(ElasticAPM.WebJobServiceName)"'
  #   env:
  #     ARM_CLIENT_ID: $(TERRAFORM-CLIENT-ID)
  #     ARM_CLIENT_SECRET: $(TERRAFORM-CLIENT-SECRET)
  #     ARM_TENANT_ID: $(TERRAFORM-TENANT-ID)
  #     ARM_SUBSCRIPTION_ID: $(TERRAFORM-SUBSCRIPTION-ID)
  #     TF_VAR_allowed_ips: $(whiteListedIps)
  #     TF_VAR_spoke_rg: $(spokeRG)
  #     TF_VAR_spoke_vnet_name: $(spokeVnetName)
  #     TF_VAR_spoke_subnet_name: $(spokeSubnetName)
  #     TF_VAR_agent_rg: $(agentRG)
  #     TF_VAR_agent_vnet_name: $(agentVnetName)
  #     TF_VAR_agent_subnet_name: $(agentSubnetName)
  #     TF_VAR_agent_subscription_id: $(agentSubscriptionId)
  #     TF_VAR_private_endpoint_subnet_name: $(privateEndpointSubnet)
  #     TF_VAR_core_services_subscription_id: $(coreServicesSubscriptionId)
  #     TF_VAR_core_services_rg: $(coreServicesRG)
