parameters:
  # If set to true, the pipeline will continue even if resources are getting destroyed. Default is false.
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    type: boolean
  # The name of the environment to be used in Azure DevOps.
  - name: AzureEnvironment
    type: string
  # The name of the Terraform workspace to use. Will also be used to generate job names and, in lower case, used to select the correct var/x-deploy.yml variable file.
  - name: ShortName
    type: string
  # The Terraform Azure PowerShell container.
  - name: Container
    type: string

jobs:
# Deploy SOLAS APIM Start
- deployment: ${{ upper(parameters.ShortName) }}DeployApimSolas
  displayName: "${{ upper(parameters.ShortName) }} - deploy SOLAS APIM"
  environment: ${{ parameters.AzureEnvironment }}   #"Ens-Dev"
  pool: $(DeploymentPool)
  container: ${{ parameters.Container }}
  workspace:
    clean: all
  variables:
    #- template: Deployment/templates/var/dev-groups.yml
    - template: var/${{ lower(parameters.ShortName) }}-groups.yml
  strategy:
    runOnce:
      deploy:
        steps:
          - template: continuous-deployment-apim.yml
            parameters:
              ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
              AzureSubscription: "UKHO-APIM-SOLAS-NonLive"
              TerraformKeyVault: $(APIM_SOLAS_TERRAFORM_KEYVAULT)
              APIMResourceGroup: $(APIM_SOLAS_RESOURCE_GROUP_NAME)
              APIMServiceInstance: $(APIM_SOLAS_SERVICE_NAME)
              tfstateStorageAccountRG: $(APIM_SOLAS_RESOURCE_GROUP_NAME)
              tfstateStorageAccountName: $(APIM_SOLAS_TFSTATE_STORAGE_ACCOUNT_NAME)
