parameters:
# If set to true, the pipeline will continue even if resources are getting destroyed. Default is false.
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    type: boolean
# The Terraform Azure PowerShell container.
  - name: Container
    type: string

jobs:
  - deployment: DevDeployApp
    # dependsOn: [DevDeployApimSolas]    # This is temperory because this job will probably  have its own template
    displayName: "Dev - deploy terraform and dotnet App"
    environment: "Ens-Dev"
    pool: $(DeploymentPool)
    container: ${{parameters.Container}}
    workspace:
      clean: all
    variables: 
    - template: Deployment/templates/var/dev-deploy.yml
      # will become var/${{ lower(parameters.ShortName) }}-deploy.yml
        
    strategy:
      runOnce:
        deploy:
          steps:
            - template: Deployment/templates/continuous-deployment.yml
              parameters:
                ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                AzureSubscription: "External Notification Service Dev - A.008.02"

            - template: Deployment/templates/continuous-deployment-apim.yml
              parameters:
                ContinueEvenIfResourcesAreGettingDestroyed: ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }}
                AzureSubscription: "UKHO-APIM-Dev"
                TerraformKeyVault: $(APIM_TERRAFORM_KEYVAULT)
                APIMResourceGroup: $(APIM_RESOURCE_GROUP_NAME)
                APIMServiceInstance: $(APIM_SERVICE_NAME)
                tfstateStorageAccountRG: $(APIM_TFSTATE_STORAGE_ACCOUNT_RG)
                tfstateStorageAccountName: $(APIM_TFSTATE_STORAGE_ACCOUNT_NAME)
                  
            - template: Deployment/templates/functional-test-process.yml
              parameters:
                TestTitle: "Dev-AutomationTests"

            - task: AzureCLI@2
              displayName: "Swap Stub URL"
              condition: always()
              inputs:
                azureSubscription: "External Notification Service Dev - A.008.02"
                scriptType: 'pscore'
                scriptLocation: 'scriptPath'
                scriptPath: '$(Pipeline.Workspace)/terraformartifact/set_stub_url.ps1'
                arguments: '-d365uri $(D365EnvApiUri) -resourceGroup $(ResourceGroup) -webappName $(WEB_APP_NAME)'
