name: auto-patch-sdk

on:
  schedule:
    - cron:  '25 21 * * TUE'
  workflow_dispatch:

jobs:
  update-sdk:
    uses: UKHO/repo-auto-patch/.github/workflows/update-dotnet-sdk.yml@v1
    with:
      work-item-title: "ENS - Auto-patch .NET SDK update"
      work-item-description: "Please review PR. Created by the auto-patch-sdk action."
      work-item-tags: "External Notification Service; TD2; Technical Debt"
    secrets:
      ado-pat: ${{ secrets.ADO_TOKEN }}
